### ISSUE TITLE
Noise files for Tensorflow are 0 bytes

### ISSUE THREAD

**Issue by JohnsonKuan** [UCSC-REAL/cifar-10-100n#1]
Hi,

I see the files below are 0 bytes.

[CIFAR-100_human_ordered.npy](https://github.com/UCSC-REAL/cifar-10-100n/blob/main/data/CIFAR-100_human_ordered.npy)
[CIFAR-10_human_ordered.npy](https://github.com/UCSC-REAL/cifar-10-100n/blob/main/data/CIFAR-10_human_ordered.npy)

I noticed this after running below from the instructions in the readme:

```
import numpy as np
noise_file = np.load('./data/CIFAR-100_human_ordered.npy', allow_pickle=True)
clean_label = noise_file.item().get('clean_label')
noise_label = noise_file.item().get('noise_label')
# The noisy label matches with following tensorflow dataloader
train_ds, test_ds = tfds.load('cifar100', split=['train','test'], as_supervised=True, batch_size = -1)
train_images, train_labels = tfds.as_numpy(train_ds) 
# You may want to replace train_labels by CIFAR-N noisy label sets
```
`UnpicklingError: Failed to interpret file './data/CIFAR-100_human_ordered.npy' as a pickle`

Thanks

**Comment by weijiaheng** [comment]
Hi Johnson,

Thanks for pointing out this issue. The tensorflow version CIFAR-N labels and image order information are updated. Feel free to let me know if any additional issue appears.

Best,
Jiaheng

**Comment by JohnsonKuan** [comment]
Hi Jiaheng,

Thanks for the quick response! Confirming that it works for me now. I can load the tensorflow version CIFAR-N files.

Best,
Johnson
