### ISSUE TITLE
Where are the individual labeling information for CIFAR-100?

### ISSUE THREAD

**Issue by yeachan-kr** [UCSC-REAL/cifar-10-100n#3]
Hello, 

Can you share the individual labeling information of each labeler for CIFAR-100? (e.g., noise_file['random_label2']) 

It will be great if they are provided as CIFAR-10-N.

Thank you.

**Comment by weijiaheng** [comment]
Hi,

The individual labeling information of each labeler for CIFAR-100 is already provided. (the path is: './data/CIFAR-100_human.pt'). As we specified in the **Readme** file, you may get CIFAR-100-N with PyTorch through:

```
import torch
noise_file = torch.load('./data/CIFAR-100_human.pt')
clean_label = noise_file['clean_label']
noisy_label = noise_file['noisy_label']
```

If you have additional concerns, please feel free to let me know.

Best,
Jiaheng
